### ISSUE TITLE
Créer un bloc pour lister les articles de blog

### ISSUE THREAD

**Issue by chris2fr** [numerique-gouv/sites-faciles#122]
Il peut être utile de lister des articles de blog dans une page selon des critères de tag, de catégorie avec une limite du nombre. Un block de type "articles-blog" peut fournir ceci.

**Comment by LucienMLD** [comment]
Exemple de présentation :
<img width="1486" alt="Capture d’écran 2024-06-18 à 15 35 50" src="https://github.com/numerique-gouv/sites-faciles/assets/22002486/fbcf6f7a-fe1b-4df2-8ea2-8e889e3e72c5">
