### ISSUE TITLE
Faire un containeur "Colonne" à l'intérieur du containeur "Colonnes"

### ISSUE THREAD

**Issue by chris2fr** [numerique-gouv/sites-faciles#124]
A l'heure actuelle, pour pouvoir ajouter plusieurs colonnes, nous sommes containts à limiter une colonne à un type de cotenu (un bloc). L'amélioration proposée serait d'introduire un bloc colonne qui peut contenir les autres blocs pour faire un contenu mixte. Je pense l'avoir fait en Wagtail déjà.

**Comment by Ash-Crow** [comment]
Bonne idée !

Il faudrait qu'on puisse fixer la largeur de la colonne au passage.
