### ISSUE TITLE
Changer l'url du "about" du github par la nouvelle ;)

### ISSUE THREAD

**Issue by gauthierna** [numerique-gouv/sites-faciles#128]
https://github.com/numerique-gouv/sites-faciles, à droite "about", c'est toujours l'url d'avant !

**Comment by chris2fr** [comment]
Bizarrement, je viens justement de ce faire sur mon dépôt bifuqué [wagtail-cfran](https://github.com/chris2fr/wagtail-cfran/) ou j'ai mis la nouvelle page home [cfran.org](https://www.cfran.org) (Cfran étant vérlan pour « français »).

Bref, le lien pour changer l'URL ne m'était pas facile à trouver. Si cela peut vous aider, c'est le rouage à côté de « A propos » ou "About". Vous le savez déjà sans doute.  Pour commodité, je reproduis ci-dessous le lien également.

https://sites-faciles.beta.numerique.gouv.fr/

![image](https://github.com/numerique-gouv/sites-faciles/assets/104329/a1320bac-9e17-45ed-b62e-764177aa022f)

Merci de votre travail !

**Comment by Ash-Crow** [comment]
Effectivement, merci !
