### ISSUE TITLE
Créer une app agenda / événements

### ISSUE THREAD

**Issue by Ash-Crow** [numerique-gouv/sites-faciles#162]
Même fonctionnement que le blog mais avec des événements.

---
Recherche de modules existants :

Une liste est présente sur https://djangopackages.org/grids/g/wagtail-calendar/

- [Wagtail-EventCalendar](https://gitlab.com/dfmeyer/wagtail_eventcalendar) → Alpha avec fonctions très limitées, pas mise à jour depuis 5 ans.
- [Joyous](https://github.com/linuxsoftware/ls.joyous) → Semble plus complet mais pas mis à jour depuis 2 ans et pas compatible avec Wagtail 4.
- [Wagtail-Meeting-Guide](https://github.com/code4recovery/wagtail-meeting-guide) → Mis à jour depuis moins d'un an, mais dédié aux réunions des Alcooliques anonymes... Comprend également des dépendances indésirables comme Google Maps.

Autres non listés : 
- [Wagtail Events](https://github.com/thclark/wagtail_events) → pas mis à jour depuis 5 ans.

**Comment by LucienMLD** [comment]
Exemple de présentation de bloc
<img width="1437" alt="Capture d’écran 2024-06-18 à 15 39 15" src="https://github.com/numerique-gouv/sites-faciles/assets/22002486/d1844e6c-1976-4d14-8778-281c70a28473">

**Comment by Ash-Crow** [comment]
Recherche de modules existants :

- https://wagtail-eventcalendar.readthedocs.io/en/latest/getting-started.html → Pas mis à jour depuis 5 ans.
