### ISSUE TITLE
Forcer le thème clair quand le sélecteur de thème est désactivé

### ISSUE THREAD

**Issue by Ash-Crow** [numerique-gouv/sites-faciles#171]
Par défaut, le site utilise le thème du navigateur, et certains sont en thème sombre.

Lorsque le sélecteur de thème est désactivé, il faudrait forcer le thème clair, certaines images s'adaptant mal au changement de thème.

**Comment by sdemagny** [comment]
Par exemple :
![Capture d’écran 2024-06-20 à 12 29 41](https://github.com/numerique-gouv/sites-faciles/assets/1196820/685eebd9-9382-4ed7-8079-565ca75d5860)

L'image en question :
![Fond_site_vitrine_2 original](https://github.com/numerique-gouv/sites-faciles/assets/1196820/fcee8994-c5fb-442a-bf9d-7a6eeefa3bc5)
