### ISSUE TITLE
Bug sur les icônes de boutons secondaires et tertiaires

### ISSUE THREAD

**Issue by JDixmier** [numerique-gouv/sites-faciles#213]
Quand j'ajoute une icône sur un bouton secondaire ou tertiaire, elle remplace complètement le texte.
Le bug ne se produit pas sur les boutons primaires.

https://www.loom.com/share/b6e5c58713df40a3a0532f50ab845374?sid=9dff59e8-a7a5-4544-8637-bb00d7c4653e

**Comment by Ash-Crow** [comment]
Hmm, c'est dû au fait que le premier bouton n'avait pas d'icône.
