### ISSUE TITLE
Quel HOST_URL et ALLOWED_HOSTS mettre dans le .env dans le cas d'un reverse proxy  pour mettre en place un HTTPS ?

### ISSUE THREAD

**Issue by teotimepacreau** [numerique-gouv/sites-faciles#223]
Bonjour,
Je fais des tests en local pour un futur usage SGAR PDL (Ministère de l'Intérieur)
Je me prends des erreurs CORS pour l'affichage des images tant que je suis sur du HTTP.
J'ai donc mis en place un reverse proxy pour rediriger vers du HTTPS (Nginx Proxy Manager).
J'ai bien rejoins le network de Nginx Proxy Manager dans le container Docker.
Cela résulte en une erreur "402 Bad Request" car je ne sais pas quelle valeur je dois mettre dans le .env pour autoriser le HOST HTTPS : dois-je mettre `www.nomdedomaine.fr` ou juste `nomdedomaine.fr`
J'ai tenté sans succès jusqu'ici :
.env : 
```
HOST_PROTO=https
HOST_URL=www.sousdomaine.nomdedomaine.fr, sousdomaine.nomdedomaine.fr, 84.247.166.00
ALLOWED_HOSTS=www.sousdomaine.nomdedomaine.fr, sousdomaine.nomdedomaine.fr, 84.247.166.00
```

**Comment by Ash-Crow** [comment]
Hmm, si c'est pour du développement en local, utiliser un sous-domaine de .localhost ne devrait pas générer d'erreurs CORS en HTTP.
