### ISSUE TITLE
Problème sur l'affichage de l'image du bloc promotionnel 

### ISSUE THREAD

**Issue by gauthierna** [numerique-gouv/sites-faciles#29]
L'image est déformée sur safari, cf : 

<img width="1403" alt="Capture d’écran 2023-04-26 à 17 10 04" src="https://github.com/betagouv/content-manager/assets/12137665/1792d489-d01b-4ffa-a0e8-4b76bd6b3bc4">

Versus chrome : 

<img width="1440" alt="Capture d’écran 2023-04-26 à 17 10 14" src="https://github.com/betagouv/content-manager/assets/12137665/43247100-b79d-4082-ad68-82001926f6a2">

**Comment by Ash-Crow** [comment]
Bonjour @gauthierna,
- Le problème est-il toujours présent avec la dernière version ?
- La capture d'écran semble montrer le bloc "Bloc image à gauche et texte à droite" et non le bloc "Section promotionnelle", est-ce bien le cas ?
