### ISSUE TITLE
Renommer le projet : CMSFR ?

### ISSUE THREAD

**Issue by bzg** [numerique-gouv/sites-faciles#60]
`content-manager` est très générique et pas très parlant.

Pour [Awesome CogeGouvFr](https://code.gouv.fr/fr/awesome/) (cc @hjonin) nous avons opté pour le nom `CMSFR`.

Est-ce que vous avez une réflexion en cours sur le nom ? Est-ce que `CMSFR` vous paraît mieux que le nom actuel ?

**Comment by Ash-Crow** [comment]
Je me demande si un nom compréhensible en français (par exemple "gestionnaire de contenus de l'État") ne serait pas plus compréhensible ?

**Comment by adipasquale** [comment]
je lis SFR dans CMSFR perso 🙄

**Comment by Ash-Crow** [comment]
Je propose de continuer cette discussion sur le Mattermost https://mattermost.incubateur.net/betagouv/pl/drkfjptiqj853ytkmio67fwxnh

**Comment by bzg** [comment]
Le nom choisi : site-facile

Je vous laisse fermer l'issue quand le renommage est effectif ?
