### ISSUE TITLE
Bug: La balise p de la description du footer ne devrait pas être présente si elle est vide

### ISSUE THREAD

**Issue by Ash-Crow** [numerique-gouv/sites-faciles#77]
Erreur 8.9.1 du RGAA

**Comment by cyrilf** [comment]
Hey, je suis tombé là un peu par hasard.

J'ai l'impression qu'il faudrait faire des changements dans le repo [django-dsfr](https://github.com/numerique-gouv/django-dsfr).

- Changer le template `footer.html` https://github.com/numerique-gouv/django-dsfr/blob/main/dsfr/templates/dsfr/footer.html#L15-L19 :
```diff
- <p class="fr-footer__content-desc">
   {% block footer_content %}
+    <p class="fr-footer__content-desc">
         {{ SITE_CONFIG.footer_description | safe }}
+    </p>
    {% endblock footer_content %}
- </p>
```

pour que la balise `p` soit incluse dans le block `footer_content` et qu'on puisse la sur-charger.
Par contre, ça ressemble un peu à un breaking change.. :unamused: 

- Mettre à jour/publier une nouvelle version

---

Modifications dans ce repo :

- Mettre à jour la dépendance vers la nouvelle version `django-dsfr`
- Mettre à jour le footer : https://github.com/numerique-gouv/content-manager/blob/main/templates/blocks/footer.html
```diff
{% block footer_content %}
+   {% if settings.content_manager.CmsDsfrConfig.footer_description %}
+     <p class="fr-footer__content-desc">
          {{ settings.content_manager.CmsDsfrConfig.footer_description | safe }}
+     </p>
+   {% endif %}
{% endblock footer_content %}
```

----

Je n'ai pas pris le temps de faire une PR parce que je suis juste de passage sur ce repo :wink: 
Il y a surement une meilleure approche qui n'implique pas de modifier `django-dsfr`.
